name: First Workflow

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  first-jobs:
     runs-on:
       - ubuntu-latest
     steps:
       - name: Print greeting
         run: echo "Hello World"

       - name: Print goodbye
         run: echo "Done - bye !"
